version: "3.9"


services: 
  minio:
    image: minio/minio
    ports:
      - "35633:35633"
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_SECRET_KEY:-minio-access-key}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minio-secret-key}
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":35633"